spring:
  datasource: # datasource 있어야 테이블 자동생성됨
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYA2imtCH5Jc5XrJpjzld5N8Ooib7lm2H0gMj3qdq8b8AlzjlzXQf6CuP1cPjGlTSEbx9OSr5wyW3YULqCK45gI1rPjreVXxErJC8CImzIGEpoNwsGXwvsAReV+wuEuHHxOFj62nCKpxnF2TjQriBY2xVu1wrQgVP/CjVtzOGK3XKdVSDfQUICNb5L+wvxVE27aYq42LMD3fEIZc3B/FNam7SCLOwT0pySnf3fsw7eWjwpC2Warqbn/Q2hUezaZfuU97lXbGXBVNRhuJ2eZYZCZ73KwfHbq8LHrlbjMeASqTuqRYiZl/GXqQE7S1WySvURTToA9kyZjNvx+l9MlBZ5Yo4Ksr26rWCSZhgjZlDwLUt7z4B2fJmqUbssSfIY1UbDVloRg3iCLaqhgtda0NkeH4LOFr+GoC0Dh/ts3pCV/V7JwagfOzycMDQt0Jb+wV4dvQAllTOCAvz68KmTBuRoituCit2Ix3e/pnfsoMIpmeXLibopsR3mLoXuUxWuS4gI2wjjm8EWLMXlAQANZuoxRkPnwkNAIUa6L0Pa+j5Ze2BA=='

token:
  expiration_time: 86400000 # 하루짜리 토큰
  secret: '{cipher}AYB/2Q9uolAbirelMMIHwtFNZC1/uGHnJXzRZamDnR/vJZTjU2pwsnYJOep3FAN7Ir3Y03xrlmh2OCzySMs3UG/n8uc4IxVc+vJsOPYMxl6mZaZK+yer0ktliPTEknV6GSHWqRWtN7RlXqf702RZQRaLSrZskBHqcGYHz2gY8aXgiyUOSjDoymB2oTGRMVyTfL4O6o1LEseGby6jvxQkfWfrV5F7BjNZDFzoWx1wLubbKx7uEF57aK6E2vno6R5MupF+2GSqug8BAAWG1yoP+hwWldmL1rCl6Q3i+YZaLY9woKmv1zW5BPyHkGUphpM7RkaMdoR3Fh9zqVDPpZP+4933UuJ28/Dg8fy0Bc1DN9D1RPjFT4WV1Vta621TzY+FIucNMQaBg/kwnVKCMi2RswubPtCb8q99zxnzxu/+ax5NKPD+1Nmj3KpNJMUv1nlX2OaR4DS09R5Njpn8NLRKW+2Og0fXctPI2hW/oFGm27qzCr6+31fp20tUKRTK68IodjKlEyyaSq3kdXtMqIO7Z2GYLuyNFOytxbdPvbdXfwonjeiRmfEc/f+xV3LA0Ui5fMw='

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders